/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymdb;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author preet
 */
public class epage2 extends javax.swing.JFrame {

    /**
     * Creates new form epage2
     */
    public epage2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(550, 210, 198, 33);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(550, 260, 198, 31);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(550, 310, 198, 31);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(550, 360, 198, 31);

        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jButton1.setText("DONE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 440, 81, 35);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("MEM ID :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 210, 129, 33);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("EQUIPMENT ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 260, 129, 31);

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("BORROW DATE :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 310, 169, 31);

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("RETURN DATE :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 360, 188, 31);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 0, 60)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PLEASE ENTER THE DETAILS!");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 20, 1010, 114);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymdb/pics/Capture2.PNG"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-30, -60, 1530, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String m=jTextField2.getText();
        String e=jTextField3.getText();
        String b=jTextField4.getText();
        String r=jTextField5.getText();
        int cop=0;
                try{
                    
                    
                    
             String sql="Insert into equilend(memid,eid,checkin,checkout)Values(?,?,?,?)";
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/gymdb","root","");
            
            CallableStatement c1=c.prepareCall("call getCount(?)");
            c1.setString(1, e);
            ResultSet r1=c1.executeQuery();
            while(r1.next())
                    {
                         cop=r1.getInt(2);
                        System.out.println(cop);
                        
                    }
            if(cop>0){
            
            
            System.out.println(cop);
            
            Statement s=c.createStatement();
            s.executeUpdate("Insert into equilend(memid,eid,checkin,checkout)Values('"+m+"','"+e+"','"+b+"','"+r+"')");
            PreparedStatement s1=c.prepareStatement("update equipment set copies=? where eid=?");
           // s.executeUpdate("update equipment set copies=? where eid=?");
            s1.setInt(1,cop-1);
            s1.setString(2,e);
            s1.execute();
                
                JOptionPane.showMessageDialog(null,"EQUIPMENT SUCCESSFULLY LENDED");
                 this.dispose();
                first f=new first();
                 f.setVisible(true);
                 f.setExtendedState(f.getExtendedState()|JFrame.MAXIMIZED_BOTH);
            }
                }
             catch (SQLException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(epage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(epage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(epage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(epage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                epage2 ep2=new epage2();
                ep2.setVisible(true);
                ep2.setExtendedState(ep2.getExtendedState()|JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
