/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymdb;

import javax.swing.JFrame;

/**
 *
 * @author preet
 */
public class facilities extends javax.swing.JFrame {

    /**
     * Creates new form facilities
     */
    public facilities() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FACILITIES PROVIDED");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 40, 760, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymdb/pics/YOGA.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 160, 180, 150);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymdb/pics/ZUM.PNG"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 160, 190, 150);

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        jLabel4.setText("YOGA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 320, 100, 30);

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        jLabel5.setText("ZUMBA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(590, 320, 120, 34);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymdb/pics/STRENGTH.PNG"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(910, 150, 190, 160);

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        jLabel7.setText("STRENGTH");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(930, 310, 140, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("BRANCH         CLASS-ID\n\n\nKORAMANGALA   1002\n\n\nINDIRANAGAR    2002\n\n\nJAYANAGAR        3002");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 360, 220, 280);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("BRANCH       CLASS-ID\n\n\nKORAMANGALA   1001\n\n\nINDIRANAGAR    2001\n\n\nJAYANAGAR        3001");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(530, 360, 220, 280);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("BRANCH        CLASS-ID\n\n\nKORAMANGALA     1003\n\n\nINDIRANAGAR     2003\n\n\nJAYANAGAR         3003\n");
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(900, 360, 230, 280);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1150, 650, 110, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymdb/pics/Capture11.PNG"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -6, 1380, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        first f=new first();
        f.setVisible(true);
        f.setExtendedState(f.getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facilities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facilities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facilities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facilities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                facilities faci=new facilities();
                faci.setVisible(true);
                faci.setExtendedState(faci.getExtendedState()|JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
